# https://aka.ms/yaml
jobs:
- job: WinTest
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
    maxParallel: '3'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    displayName: Install prerequisites

  - script: |
      python -m pip install flake8
      flake8 xbbg
    displayName: Run Lint Tests

  - script: |
      pip install pytest pytest-cov coverage codecov
      pytest xbbg --doctest-modules --cov -v
    displayName: Run Doctests and Coverages
