name: Auto CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BLPAPI_ROOT: /home/bbg
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov codecov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --extend-ignore=E701,E501 xbbg
    - name: Test with pytest
      run: |
        pytest --doctest-modules --cov -v xbbg
    - name: Coverage report
      run: |
        codecov --token=ff17768d-30bd-4917-98f2-a011606597ea
